from abc import ABC, abstractmethod
import os
import time
import threading
from pathlib import Path
from typing import List, Literal, TypeVar, Generic, Any
import hashlib

from memory.state.state import *
from memory.IR.U6IR import *
from utility.logger import Logger
from memory.utils.function import Function
from memory.utils.value import Value

BASE_PATH = Path(__file__).resolve().parents[2]

S = TypeVar("S", bound=State)


class Agent(ABC, Generic[S]):
    """Base class for agents that perform scanning operations.

    An agent accesses and potentially transforms the U6IR (Universal IR) during scanning.
    It analyzes the code represented in the U6IR and may modify it to add analysis results.
    The agent also maintains its own state to store additional outputs like:
    - Bug reports from bug detection (e.g., BugScanAgent, DFBScanAgent, PropScanAgent)
    - Program slices from slicing analysis (e.g., SliceScanAgent)
    - Semantic indexes for code understanding (e.g., SemIndexScanAgent)
    """

    def __init__(
        self,
        project_path: str,
        language: Literal["C", "Cpp", "Java", "Python", "Go"],
        u6ir: U6IR,
        audit_model_name: str,
        temperature: float,
        max_query_num: int,
        state: S,
    ) -> None:
        """
        Initialize the agent.

        Args:
            project_path: Path to the project to analyze
            language: Programming language of the project
            u6ir: U6IR instance for metadata extraction
            audit_model_name: Name of the LLM model for audit
            temperature: Temperature parameter for LLM
            max_query_num: Maximum number of queries to send to the LLM
            state: State of the agent
        """
        self.project_path = project_path
        self.project_name = project_path.split("/")[-1]

        # XXX (ZZ): to make mypy happy
        self.language: Literal["Cpp", "Java", "Python", "Go"]
        if language in {"C", "Cpp"}:
            self.language = "Cpp"
        else:
            assert language != "C"
            self.language = language

        self.u6ir = u6ir
        self.audit_model_name = audit_model_name
        self.temperature = temperature
        self.max_query_num = max_query_num
        self.state = state

        self.agent_name = self.__class__.__name__
        self.dependency_agents: List["Agent"] = []
        self.lock = threading.Lock()

        if self.lock:
            self.start_time_str = time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime())
            self.hash_id = hashlib.sha256(f"{id(self)}".encode()).hexdigest()[0:6]
            self.log_dir_path = f"{BASE_PATH}/log/{self.agent_name}/{self.audit_model_name}/{self.language}/{self.project_name}/{self.start_time_str}-{self.hash_id}"
            os.makedirs(self.log_dir_path, exist_ok=True)
            self.logger = Logger(self.log_dir_path + "/" + "agent.log")

            # Set up result directory
            self.res_dir_path = f"{BASE_PATH}/result/{self.agent_name}/{self.audit_model_name}/{self.language}/{self.project_name}/{self.start_time_str}-{self.hash_id}"
            os.makedirs(self.res_dir_path, exist_ok=True)

    def run(self) -> U6IR:
        """Run the agent."""
        self.scan()
        self.u6ir = self.finalize()
        return self.u6ir

    @abstractmethod
    def scan(self) -> None:
        """Start the scanning process."""
        pass

    @abstractmethod
    def finalize(self) -> U6IR:
        """Finalize the scanning process for persistence."""
        pass

    def get_agent_state(self) -> S:
        """Get the state of the agent.

        Returns:
            State: The agent state
        """
        return self.state

    def add_dependent_agent(self, agent: "Agent[Any]") -> None:
        """Add a dependent agent"""
        self.dependency_agents.append(agent)

    def get_log_files(self) -> List[str]:
        """Get list of log files generated by this agent and the agents it depends on.

        Returns:
            List[str]: List of log file paths
        """
        all_log_file_paths = []
        for sub_agent in self.dependency_agents:
            all_log_file_paths.extend(sub_agent.get_log_files())
        all_log_file_paths.append(self.log_dir_path + "/" + "agent.log")
        return all_log_file_paths
